[build]
  publish = "public"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods= "*"

[[edge_functions]]
path = "/test"
function = "hello"

[[edge_functions]]
path = "/submit"
function = "submit"